In [26]:
import pandas as pd
df = pd.read_csv('Dataset Langit Musik.csv')
df.head()

,updated_date,year,month,msisdn,first_date_transaction,last_date_transaction,recency,frequency,duration,recency_score,...,avg_album_category,jumlah_genre,avg_genre_category,los,los_cat,play_pattern,province,channel_name,product_name,payment_name
0,2020-03-30,2020,3,811101518,2019-12-07,2019-12-28,89,2,124,2,...,1. 1 album,2,1. 1 genre,1091,6.>2y,1-1-1-0-0,Jakarta Raya,LangitMusik Web WAP Client,LangitMusik Streaming,TELKOMSEL
1,2020-03-30,2020,3,811101722,2020-01-29,2020-01-29,57,2,28,3,...,1. 1 album,1,1. 1 genre,396,5.1y-2y,0-0-0-1-0,Daerah Khusus Ibukota Jakarta,Langitmusik Android,LangitMusik Premium,TELKOMSEL
2,2020-03-30,2020,3,811105399,2019-12-04,2019-12-04,113,3,284,1,...,2. 2-5 albums,1,1. 1 genre,1026,6.>2y,1-1-0-0-0,Daerah Khusus Ibukota Jakarta,LangitMusik Web WAP Client,LangitMusik Streaming,TELKOMSEL
3,2020-03-30,2020,3,811107334,2019-11-09,2019-11-09,138,12,1724,1,...,3. 5-10 albums,4,2. 2-5 genres,367,5.1y-2y,0-0-0-0-0,Daerah Khusus Ibukota Jakarta,LangitMusik Web WAP Client,LangitMusik Streaming,TELKOMSEL
4,2020-03-30,2020,3,8111107755,2019-11-29,2019-12-03,114,15,2280,1,...,2. 2-5 albums,5,2. 2-5 genres,478,5.1y-2y,1-1-0-0-0,Jawa Tengah,LangitMusik Web WAP Client,LangitMusik Streaming,TELKOMSEL

In [27]:
column = ['updated_date', 'year','month', 'msisdn', 'first_date_transaction', 'last_date_transaction']
df.drop(column,inplace=True, axis=1)
df.head()

,recency,frequency,duration,recency_score,recency_segment,frequency_score,frequency_segment,duration_score,duration_segment,rfd,...,avg_album_category,jumlah_genre,avg_genre_category,los,los_cat,play_pattern,province,channel_name,product_name,payment_name
0,89,2,124,2,L,1,L,1,L,LLL,...,1. 1 album,2,1. 1 genre,1091,6.>2y,1-1-1-0-0,Jakarta Raya,LangitMusik Web WAP Client,LangitMusik Streaming,TELKOMSEL
1,57,2,28,3,M,1,L,1,L,MLL,...,1. 1 album,1,1. 1 genre,396,5.1y-2y,0-0-0-1-0,Daerah Khusus Ibukota Jakarta,Langitmusik Android,LangitMusik Premium,TELKOMSEL
2,113,3,284,1,L,1,L,1,L,LLL,...,2. 2-5 albums,1,1. 1 genre,1026,6.>2y,1-1-0-0-0,Daerah Khusus Ibukota Jakarta,LangitMusik Web WAP Client,LangitMusik Streaming,TELKOMSEL
3,138,12,1724,1,L,1,L,1,L,LLL,...,3. 5-10 albums,4,2. 2-5 genres,367,5.1y-2y,0-0-0-0-0,Daerah Khusus Ibukota Jakarta,LangitMusik Web WAP Client,LangitMusik Streaming,TELKOMSEL
4,114,15,2280,1,L,1,L,2,L,LLL,...,2. 2-5 albums,5,2. 2-5 genres,478,5.1y-2y,1-1-0-0-0,Jawa Tengah,LangitMusik Web WAP Client,LangitMusik Streaming,TELKOMSEL

In [76]:
df1 = df.filter(['province','channel_name','product_name','hour_cat_play','day_play_cat','avg_play_category','duration'], axis=1)
df1.head()

,province,channel_name,product_name,hour_cat_play,day_play_cat,avg_play_category,duration
0,Jakarta Raya,LangitMusik Web WAP Client,LangitMusik Streaming,sore,weekend,1. <5 plays,124
1,Daerah Khusus Ibukota Jakarta,Langitmusik Android,LangitMusik Premium,malam,weekday,1. <5 plays,28
2,Daerah Khusus Ibukota Jakarta,LangitMusik Web WAP Client,LangitMusik Streaming,siang,weekday,1. <5 plays,284
3,Daerah Khusus Ibukota Jakarta,LangitMusik Web WAP Client,LangitMusik Streaming,sore,weekend,2. 5-15 plays,1724
4,Jawa Tengah,LangitMusik Web WAP Client,LangitMusik Streaming,sore,weekday,2. 5-15 plays,2280

In [77]:
df2=df1.groupby(['province', 'channel_name'], as_index=False)['duration'].count()
df2.head()
df4=df1.groupby(['channel_name','product_name'], as_index=False)['duration'].count()
df4.head()
df5=df1.groupby(['product_name','hour_cat_play'], as_index=False)['duration'].count()
df5.head()
df6=df1.groupby(['hour_cat_play','day_play_cat'], as_index=False)['duration'].count()
df6.head()
df7=df1.groupby(['day_play_cat','avg_play_category'], as_index=False)['duration'].count()
df7.head()

  day_play_cat avg_play_category  duration
0      weekday       1. <5 plays       146
1      weekday     2. 5-15 plays        94
2      weekday    3. 15-30 plays        79
3      weekday    4. 30-60 plays        46
4      weekday      5. >60 plays         9

In [78]:
df2.columns = ['a', 'b', 'Quantity']
df3.columns = ['a', 'b', 'Quantity']
df4.columns = ['a', 'b', 'Quantity']
df5.columns = ['a', 'b', 'Quantity']
df6.columns = ['a', 'b', 'Quantity']
df7.columns = ['a', 'b', 'Quantity']
df8 = df2.append(df3)
df9 = df8.append(df4)
df10 = df9.append(df5)
df11 = df10.append(df6)
df12 = df11.append(df7)
df12

           a                           b  Quantity
0   Ar Riyad  LangitMusik Web WAP Client         1
1       Bali  LangitMusik Web WAP Client         2
2       Bali         Langitmusik Android         9
3     Banten  LangitMusik Web WAP Client         9
4     Banten         Langitmusik Android         2
..       ...                         ...       ...
5    weekend                 1. <5 plays        25
6    weekend               2. 5-15 plays        62
7    weekend              3. 15-30 plays        30
8    weekend              4. 30-60 plays         7
9    weekend                5. >60 plays         2

[98 rows x 3 columns]

In [79]:
import plotly
import plotly.plotly as py

In [89]:
def genSankey(df,cat_cols=[],value_cols='',title='Sankey Diagram'):
    # maximum of 6 value cols -> 6 colors
    colorPalette = ['#646464','#FFD43B','#4B8BBE','#306998','#DE6E4B','#7FD1B9']
    labelList = []
    colorNumList = []
    for catCol in cat_cols:
        labelListTemp =  list(set(df[catCol].values))
        colorNumList.append(len(labelListTemp))
        labelList = labelList + labelListTemp
        
    # remove duplicates from labelList
    labelList = list(dict.fromkeys(labelList))
    
    # define colors based on number of levels
    colorList = []
    for idx, colorNum in enumerate(colorNumList):
        colorList = colorList + [colorPalette[idx]]*colorNum
        
    # transform df into a source-target pair
    for i in range(len(cat_cols)-1):
        if i==0:
            sourceTargetDf = df[[cat_cols[i],cat_cols[i+1],value_cols]]
            sourceTargetDf.columns = ['source','target','count']
        else:
            tempDf = df[[cat_cols[i],cat_cols[i+1],value_cols]]
            tempDf.columns = ['source','target','count']
            sourceTargetDf = pd.concat([sourceTargetDf,tempDf])
        sourceTargetDf = sourceTargetDf.groupby(['source','target']).agg({'count':'sum'}).reset_index()
        
    # add index for source-target pair
    sourceTargetDf['sourceID'] = sourceTargetDf['source'].apply(lambda x: labelList.index(x))
    sourceTargetDf['targetID'] = sourceTargetDf['target'].apply(lambda x: labelList.index(x))
    
    # creating the sankey diagram
    data = dict(
        type='sankey',
        node = dict(
          pad = 15,
          thickness = 20,
          line = dict(
            color = "black",
            width = 0.5
          ),
          label = labelList,
          color = colorList
        ),
        link = dict(
          source = sourceTargetDf['sourceID'],
          target = sourceTargetDf['targetID'],
          value = sourceTargetDf['count']
        )
      )
    
    layout =  dict(
        title = title,
        font = dict(
          size = 10
        )
    )
    
    fig = dict(data=[data], layout=layout)
    return fig

In [90]:
fig = genSankey(df12,cat_cols=['a','b'],value_cols='Quantity',title='Sankey Diagram')
plotly.offline.plot(fig, validate=False)

UnboundLocalError: local variable 'data' referenced before assignment